import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { useAuth } from './hooks/useAuth';
import { ReactNode } from 'react';

const inter = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Authentication App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // useAuth();

  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
