import { Button } from "@/styles/components/button"
import Head from "next/head"
import Router from "next/router"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This is the homepage</h1>
        <Button onClick={() => Router.push("/signin")}>Sign in</Button>
      </main>
    </>
  )
}
